In [1]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

In [2]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
import numpy as np
vect_a = np.array(a)
vect_b = np.array(b)

In [4]:
vect_a + vect_b

array([ 7,  9, 11, 13, 15])

## Vector Norm

In [5]:
vect_a = np.array([3,4])
np.linalg.norm(vect_a, 1)

7.0

## Operasi Penjumlahan/Pengurangan/Pembagian

In [6]:
a = [1,2,3]
vect_a = np.array(a)
vect_a

array([1, 2, 3])

In [7]:
vect_a / 2

array([0.5, 1. , 1.5])

In [8]:
vect_a + 2

array([3, 4, 5])

## Antar Vector

### Dengan Bilangan

In [9]:
b = [10, 11, 12]
vect_b = np.array(b)
vect_b

array([10, 11, 12])

In [10]:
vect_a / vect_b

array([0.1       , 0.18181818, 0.25      ])

### Antar Bilangan

In [11]:
c = [10, 11]
vect_c = np.array(c)
vect_c

array([10, 11])

In [13]:
# vect_a + vect_c # akan error karena beda ukuran

## Perkalian

In [14]:
# Dengan Bilangan
vect_a *2

array([2, 4, 6])

In [15]:
print(vect_a)
print(vect_b)

[1 2 3]
[10 11 12]


In [16]:
vect_a * vect_b

array([10, 22, 36])

In [17]:
vect_a.dot(vect_b)

68

In [18]:
np.dot(vect_a, vect_b)

68

In [19]:
vect_a@vect_b

68

## Cosine Similarity

In [20]:
vect_f = np.array([4,0])
vect_g = np.array([6,0])

In [28]:
cos_theta = (vect_f.dot(vect_g))/ (np.linalg.norm(vect_f) * np.linalg.norm(vect_g))
cos_theta

1.0

In [30]:
rad = np.arccos(cos_theta)
rad

0.0

In [32]:
degree = np.degrees(rad)
degree

0.0

## Studi Kasus

teks_1 = saya pergi ke rumah nenek saya
teks_2 = saya pergi ke rumah kakek saya

In [36]:
teks_1 = [2, 1, 1, 1, 1, 0]
teks_2 = [2, 1, 1, 1, 0, 1]

vect_t1 = np.array(teks_1)
vect_t2 = np.array(teks_2)

In [39]:
cos_theta = (vect_t1.dot(vect_t2)) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

0.8749999999999998

## Studi Kasus 2

```
teks_3 = Selamat pagi dunia
teks_4 = Nusantara ibu kota baru
```

In [40]:
teks_3 = [1, 1, 1, 0, 0, 0, 0]
teks_4 = [0, 0, 0, 1, 1, 1, 1]

vect_t3 = np.array(teks_3)
vect_t4 = np.array(teks_4)

In [43]:
cos_theta = (vect_t3.dot(vect_t4)) / (np.linalg.norm(vect_t3) * np.linalg.norm(vect_t4))
cos_theta

0.0

```
teks_5 = Selamat pagi ibu dunia
teks_6 = Nusantara ibu kota baru
```

In [44]:
teks_5 = [1, 1, 1, 0, 1, 0, 0]
teks_6 = [0, 0, 0, 1, 1, 1, 1]

vect_t5 = np.array(teks_5)
vect_t6 = np.array(teks_6)

In [45]:
cos_theta = (vect_t5.dot(vect_t6)) / (np.linalg.norm(vect_t5) * np.linalg.norm(vect_t6))
cos_theta

0.25