# Day 2 AM // Matrix

## Pendefinisian Matriks

Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung.

Tidak seperti vektor yang merupakan list satu dimensi, sebaliknya matriks adalah list dua dimensi yang terdiri dari baris dan kolom.

In [1]:
# Pendefinisian vektor dan elemennya
u = [1, 3, 5] # ada 3 elemen pada vektor u

afif = [175, 73] # ada 2 elemen dalam vektor
budi = [170, 68]
deden = [180, 78]

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$

Mendefinisikan matriks A

In [1]:
import numpy as np

In [3]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [5]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [2]:
# Pendefinisian matriks dan dimensinya
data_1 = [1,2,3] # Array 1 dimensi, di dalam array langsung data, tidak ada array lagi
data_2 = [[1,2,3], [4,5]] # Array 2 dimensi tapi bukan matriks, tidak bisa dijadikan matriks karena beda jumlah elemen
data_3 = [[1,2,3], [4,5,6]]

# Pendefinisian matriks data_1 dengan menggunakan NumPy
import numpy as np
vec = np.array(data_1)
vec

# Pendefinisian matriks data_2
## data = np.array(data_2)
## data
## tidak mampu membuat ini menjadi matriks karena beda jumlah elemen

array([1, 2, 3])

In [3]:
# Pendefinisian matriks data_3

mat = np.array(data_3)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Pendefinisian matriks dengan menyebutkan list terlebih dahulu

data = [[1,2], [3,4], [5,6], [7,8]] # pastikan jumlah elemen di list dalam sama
data_mat = np.array(data)
data_mat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
# Pendefinisian matriks secara langsung dalam variabel

v = np.array([[1,2,3], [1,0,3]])
v

array([[1, 2, 3],
       [1, 0, 3]])

## Types of Matrix

1. Square Matrix *X(m,m)*   : X=array([4,92], [3,5,7], [8,1,6])
2. Upper Triangle matrix    : np.triu(X)
3. Lower Triangle matrix    : np.tril(X)
4. Diagonal Matrix          : np.diag(X)
5. Identity Matrix          : np.eye(shape)

## Operasi Aritmatika

### Penjumlahan Matriks

Matriks dapat dijumlahkan atau dikurangkan dengan matriks lain. Penambahan/pengurangan akan dilakukan pada setiap elemen. Ukuran matriks harus sama. Misalkan kedua matriks harus sama memiliki ukuran 3x2.

In [6]:
# Operasi Penjumlahan Antar Matriks

## Pendefinisian matriks A

A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
A = np.array(A)

## Pendefinisian matriks C

C = [[7,8,9],
     [9,8,7]]
C = np.array(C)

# A + C tidak bisa dioperasikan karena beda jumlah elemen

In [7]:
# Operasi Penjumlahan Antar Matriks

B = [[7,8,9],
     [9,8,7],
     [3,4,5]]
B = np.array(B)

A + B

array([[ 8, 10, 12],
       [13, 13, 13],
       [10, 12, 14]])

### Pengurangan Matriks

In [8]:
# Operasi Pengurangan Antar Matriks

## Pendefinisian matriks A

A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
A = np.array(A)

## Pendefinisian matriks B

B = [[7,8,9],
     [9,8,7],
     [3,4,5]]
B = np.array(B)

A-B

array([[-6, -6, -6],
       [-5, -3, -1],
       [ 4,  4,  4]])

### Perkalian Matriks

Ada tiga cara untuk melakukan perkalian matriks, yaitu matriks dengan bilangan, perkalian hadamard, dan antar matriks. 

Untuk melakukan perkalian matriks dengan skalar, cukup kalikan setiap elemen dengan skalar. Misalkan kita memiliki matriks 3x2.

In [9]:
# Operasi Perkalian Matriks dengan Bilangan

3*A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

Pada dasarnya perkalian Hadamard tidak jauh berbeda dengan perkalian vektor – vektor. Operasi dilakukan berdasarkan elemen. Simbol perkalian akan dinotasikan dengan (*).

In [10]:
# Operasi Perkalian Hadamard Product (element wise multiplication)

A * B 

array([[ 7, 16, 27],
       [36, 40, 42],
       [21, 32, 45]])

Perkalian antar matriks berbeda dengan perkalian lainnya dan cukup rumit. Operasi harus mengikuti aturan bahwa jumlah kolom pada matriks pertama harus sama dengan jumlah baris pada matriks kedua.

In [11]:
# Cara 1 : Operasi Perkalian Antar Matrix

A @ B 

array([[ 34,  36,  38],
       [ 91,  96, 101],
       [148, 156, 164]])

In [12]:
# Cara 2 : Operasi Perkalian Antar Matrix

np.dot(A,B)

array([[ 34,  36,  38],
       [ 91,  96, 101],
       [148, 156, 164]])

In [13]:
# Contoh Operasi Perkalian Antar Matrix

C = [[1,2],
     [3,4],
     [5,6]]
C = np.array(C)

D = [[5,6,7],
     [8,9,3]]
D = np.array(D)

C @ D

array([[21, 24, 13],
       [47, 54, 33],
       [73, 84, 53]])

### Pembagian Matriks

Pembagian matriks dilakukan sama seperti pembagian vektor dan perkalian Hadamard.

In [14]:
# Pembagian Dengan Bilangan

A/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ],
       [2.33333333, 2.66666667, 3.        ]])

In [15]:
# Pembagian Hadamard Product (element wise)

A / B

array([[0.14285714, 0.25      , 0.33333333],
       [0.44444444, 0.625     , 0.85714286],
       [2.33333333, 2.        , 1.8       ]])

## Transpose

Matriks dapat ditransposisikan. Transpose matriks artinya membuat matriks baru dengan jumlah kolom dan baris yang dibalik atau ditranspose. Ini dilambangkan dengan superskrip T di sebelah matriks A^T .

In [16]:
# Transpose Matriks

A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Invers

Invers matriks adalah proses mencari matriks lain yang jika dikalikan dengan matriks tersebut akan menghasilkan matriks identitas. Operasi pembalik suatu matriks ditunjukkan oleh superskrip 1 di sebelah matriks; misalnya, A−1. Hasil dari operasi tersebut disebut sebagai invers dari matriks aslinya; misalnya, B adalah kebalikan dari A. 

Operasi invers matriks tidak dihitung secara langsung, melainkan matriks terbalik ditemukan melalui operasi numerik, di mana serangkaian metode yang efisien dapat digunakan, sering kali melibatkan bentuk dekomposisi matriks.

In [17]:
# Operasi Invers Matriks
## Pendefinisian Matriks A
A = np.array([[1,2], [7,8]])

## Pendefinisian invers dengan menggunakan numpy.linalg
from numpy.linalg import inv
inv_A = inv(A)
inv_A

array([[-1.33333333,  0.33333333],
       [ 1.16666667, -0.16666667]])

In [18]:
# Perkalian Invers dengan Matriks
## Hasil outputnya adalah matriks identitas

A @ inv_A

array([[1., 0.],
       [0., 1.]])

## Determinant

Determinan menggambarkan geometri relatif dari vektor-vektor yang menyusun baris-baris matriks. Lebih khusus lagi, determinan matriks A memberi tahu Anda volume sebuah kotak dengan sisi-sisi yang diberikan oleh baris-baris A.

Determinant dilambangkan dengan notasi det(A) atau |A|, di mana A adalah matriks tempat kita menghitung determinan. 

Matriks untuk operasi determinant harus matriks persegi.

Determinant hanya digunakan untuk mendeteksi matriks punya invers atau tidak.

In [19]:
# Operasi Determinan

from numpy.linalg import det
B = np.array([[1,2],[2,5]])
det(B)

1.0

## Tensor

Tensor adalah generalisasi dari vektor dan matriks dan mudah dipahami sebagai array multidimensi. Vektor adalah tensor orde satu atau orde satu dan matriks adalah tensor orde dua atau orde dua.

Tensor bisa dikatakan matriks yang ada di dalam list.

Tensor biasanya array 3 dimensi.

In [21]:
# Pendefinisian Tensor

## Pendefinisian Matriks
A = np.array([[1,2], [7,8]])
B = np.array([[1,1], [1,1]])

In [29]:
## Melihat ukuran A

A.shape

(3, 2)

In [30]:
## Melihat ukuran B

B.shape

(3, 2)

In [31]:
## Operasi Tensor

tensor = [A, B]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [7, 8],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

Contoh lain:

In [32]:
## Pendefinisian Matriks

A = np.array([[1,2], [7,8], [1,1]])
B = np.array([[1,1], [1,1], [1,1]])
C = np.array([[1,1], [1,1], [1,1]])

In [34]:
# Pendefinisian Tensor

tensor = [A, B, C]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [7, 8],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [35]:
# Mencari ukuran tensor

tensor.shape

(3, 3, 2)

---

**LATIHAN 1** 

Hitunglah $A ^ 2 - 2 A + 3$ pada:

$$A = 
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

## Solving Matrix equations

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1 
\end{pmatrix}
$$

Mendefinisikan matriks dengan NumPy:

In [6]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

Menggunakan fungsi `linalg.solve`:

In [7]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

Hasilnya yang diperoleh:

In [8]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

---

**LATIHAN 2** 

Hitung persamaan matriks $Bx=b$ (menggunakan $B$ yang didefinisikan sebelumnya).

---

## Matrix inversion and determinants

Menghitung invers suatu matriks:

In [9]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

Mendefinisikan Ainv menjadi : $A^{-1}A=\mathbb{1}$:

In [10]:
A * Ainv

matrix([[ 1.00000000e+00,  2.77555756e-17,  3.05311332e-16],
        [-2.08166817e-16,  1.00000000e+00, -2.08166817e-16],
        [ 5.55111512e-17, -5.55111512e-17,  1.00000000e+00]])

Matriks tersebut tidak terlihat seperti matriks identitas tetapi jika dilihat lebih teliti, semua diagonalnya adalah `1` dan diagonal yang tidak aktif adalah angka **sangat** kecil (yang dari sudut pandang komputer adalah `0`) .

Menghitung determinant:

In [11]:
np.linalg.det(A)

-128.99999999999997