# Non-Graded Challenge 4

Buatlah Tensor dibawah ini dengan Python:

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \ 99 & 43 \end{bmatrix} \ \begin{bmatrix} 75 & 21 \ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \ 18 & 84 \end{bmatrix} \end{bmatrix} $$

In [1]:
# Mendefinisikan tensor menggunakan Numpy

import numpy as np

Z = np.array([[[23, 50], 
               [7,12]], 

              [[57, 67], 
               [99, 43]], 

              [[75, 21], 
               [57, 12]], 
               
              [[87, 26], 
               [18, 84]]])
Z

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [2]:
# Melihat ukuran tensor Z

Z.shape

(4, 2, 2)

Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$

In [3]:
# Operasi Perkalian Antar Matrix

# Mendefinisikan Matriks A
A = [[23, 50, 19], 
     [7, 12, 109], 
     [57, 67, 98]]
A = np.array(A)

# Mendefinisikan Matriks B
B = [17, 22, 19]
B = np.array(B)

In [4]:
## Mencari ukuran matriks A

A.shape

(3, 3)

In [5]:
## Mencari ukuran matriks B

B.shape

(3,)

Karena jumlah kolom A = jumlah baris kolom B, maka A dan B bisa dikalikan.

In [6]:
## Perkalian antar Matriks 

A @ B

array([1852, 2454, 4305])

Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} $$

In [7]:
# Mendefinisikan Matriks A
A = [[23, 50, 19], 
     [7, 12, 109], 
     [57, 67, 98]]
A = np.array(A)

# Menampilkan Matriks A sebelum ditranspose
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [8]:
# Transpose Matriks A

A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [11]:
# Determinan menggunakan numpy.linalg

from numpy.linalg import det
det(A)

131344.0000000002

In [12]:
# Invers menggunakan numpy.linalg

from numpy.linalg import inv
inv_A = inv(A)
inv_A

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])