# Non-Graded Challenge 3

1. Buatlah Vector dibawah ini dengan Python:

$$ \begin{bmatrix} 17 
                \  22 
                \  19 \end{bmatrix} $$

In [1]:
import numpy as np

In [2]:
z = [17, 22, 19]

In [3]:
vect_z = np.array(z)
vect_z

array([17, 22, 19])

2. Diberikan 3 buah vektor 3 dimensi: $$ A= \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} ,B= \begin{bmatrix} 10 \ 20 \ 11 \end{bmatrix}, C= \begin{bmatrix} 5 \ 12 \ 9 \end{bmatrix} $$


In [4]:
A = [12, 22, 19]
B = [10, 20, 11]
C = [5, 12, 9]

In [5]:
vect_A = np.array(A)
vect_B = np.array(B)
vect_C = np.array(C)

In [6]:
# Hitung A+B
vect_A + vect_B

array([22, 42, 30])

In [7]:
# Hitung B - C
vect_B + vect_C

array([15, 32, 20])

In [8]:
# A dot C
vect_A.dot(vect_C)

495

In [9]:
# A x B
vect_A * vect_B

array([120, 440, 209])

In [10]:
# norm A
np.linalg.norm(vect_A)

31.448370387032774

In [11]:
# Mencari cos theta
cos_theta = (vect_A.dot(vect_B))/ (np.linalg.norm(vect_A) * np.linalg.norm(vect_B))
cos_theta

0.9812561550208765

In [12]:
# Mencari radian
rad = np.arccos(cos_theta)
rad

0.19392109076664962

In [13]:
# Sudut antara vektor A dan B
degree = np.degrees(rad)
degree

11.11086005950238