# Week 1: Day 3 PM // Numpy

NumPy (**Num**erical **Py**thon) adalah library Python yang fokus pada scientific computing. NumPy memiliki kemampuan untuk membentuk objek N-dimensional array, yang mirip dengan list pada Python. Keunggulan NumPy array dibandingkan dengan list pada Python adalah konsumsi memory yang lebih kecil serta runtime yang lebih cepat. NumPy juga memudahkan kita pada Aljabar Linear, terutama operasi pada Vector (1-d array) dan Matrix (2-d array).

List pada Python tidak mendukung penuh kemudahan scientific computing, sebagai contoh kita akan lakukan operasi penjumlahan pada 2 list.

Numpy biasanya untuk komputasi, untuk array Numpy lebih cepat dibandingkan pakai list. Numpy juga digunakan Untuk membentuk vektor, matriks.

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

NumPy juga menyediakan metode seperti one(), zeros(), dan lain-lain.

In [61]:
# you can easily create an array filled with 0s:

np.zeros(3)

array([0., 0., 0.])

In [63]:
# Or an array filled with 1s:


np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [64]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty(0)
#yang diperoleh acak
#py -m pip install numpy, untuk install numpy

array([], dtype=float64)

In [66]:
# You can create an array with a range of elements

print(np.arange(2,10,2)) #mirip dengan list
print(np.arange(2))

[2 4 6 8]
[0 1]


### Perbedaan list dengan Numpy


In [10]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
# weight/height**2 --> akan error karena list tidak bisa dioperasikan secara langsung

In [11]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_height = np.array(height)
np_weight = np.array(weight)
np_weight/np_height**2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [12]:
height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
weight/height**2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

### Add, Remove, and Sort

```py
np.append()
np.delete()
np.sort()
```

`arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])`

Kamu dapat menambahkan elements pada array dengan menggunakan `np.append()`. Pastikan untuk menentukan array dan nilainya.

In [13]:
arr= np.array ([1,2,3,4,5])
np.append(arr, (6,7,8)) #append untuk memasukkan nilai
#jangan menamakan variabel dengan nama modul, fungsi, list. dll.

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arr = np.array([1,3,7,5])
np.append(arr, (6,7,8))

array([1, 3, 7, 5, 6, 7, 8])

Kamu bisa menghapus dengan `np.delete()`: 

In [15]:
np.delete(arr,3)

array([1, 3, 7])

Kamu bisa mengurutkan dengan `np.sort()`:

In [68]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [69]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

```py
ndarray.ndim()
ndarray.size()
ndarray.shape()
```

`ndarray.ndim` menampilkan jumlah axes atau dimensi.

`ndarray.size` menampilkan jumlah total elemen

`ndarray.shape` menampilkan tuple bilangan bulan yang menunjukkan jumlah elemen. Jika data memiliki array 2D dengan 2 baris dan 3 kolom, maka bentuk arraynya adalah (2,3).

In [17]:
array_1 = np.array([[[1,2,3,4,5],
                    [6,7,8,9,10]],

                    [[11,12,13,14,15],
                    [16,17,18,19,20]],

                    [[21,22,23,24,25],
                    [26,27,28,29,30]]])
print(array_1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [18]:
array_1.ndim

3

In [19]:
array_1.size

30

In [20]:
array_1.shape

(3, 2, 5)

In [21]:
scalar = np.array(32)
print(scalar) #0D

32


In [70]:
vektor = np.array([1,2,3,4])
print(vektor)

[1 2 3 4]


In [23]:
matriks= np.array([[1,2,3,4],
                    [5,6,7,8]])
print(matriks)
matriks.shape #(baris, kolum)

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

### Reshape

```py
np.reshape()
```

In [24]:
#reshape untuk mengubah pola
#vektornya diubah menjadi bentuk matriks
a = np.arange(6)

print(a) # 1 baris 5 kolum

[0 1 2 3 4 5]


In [25]:
b = a.reshape(3,2) #menjadi 3 baris 2 kolum

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [26]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [27]:
# a.reshape(5,1) # akan error karena tidak sesuai ukurannya

Dengan np.reshape, kita dapat menentukan beberapa parameter opsional:

`numpy.reshape(a, newshape, order)`

- **a** adalah array yang akan dibentuk ulang.
- **newshape** adalah bentuk baru yang diinginkan. Kita dapat menentukan bilangan bulat atau tupel bilangan bulat. Jika kita menentukan bilangan bulat, hasilnya akan berupa array dengan panjang ttt. Bentuknya harus sesuai dengan bentuk aslinya.
- **order**: 'C' artinya membaca/menulis elemen menggunakan urutan indeks mirip C, 'F' artinya membaca/menulis elemen menggunakan urutan indeks mirip Fortran, 'A' artinya membaca/menulis elemen elemen dalam urutan indeks seperti Fortran jika a adalah Fortran bersebelahan dalam memori, urutan seperti C sebaliknya.

### Convert 1D to 2D

```py
np.newaxis
np.expand_dims
```

In [71]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [72]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [29]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[0 1 2 3 4 5]]


In [73]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Kita juga bisa memperluas array dengan menyisipkan new axis pada posisi tertentu dengan np.expand_dims.

In [30]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [31]:
b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [32]:
b.shape[0]

6

In [33]:
b.shape[1]

1

In [74]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [35]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and Slicing

In [36]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [75]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [77]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [37]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[2 4 6]


In [78]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

```py
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()
```

In [79]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [38]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [39]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [40]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [82]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([1, 2, 3, 4, 5, 6])

In [42]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([1, 2, 3, 4, 5, 6])

### Basic array operations

`Addition, subtraction, multiplication, division, and more`

You can add the arrays together with the plus sign.

`data + ones`

You can, of course, do more than just addition.

```py
data - ones
data * data
data / data
```

In [43]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [44]:
b = np.array([[2, 1], [2, 2]])
b

array([[2, 1],
       [2, 2]])

In [45]:
# You can sum the rows

b.sum(axis=0) #baris

array([4, 3])

In [46]:
b.shape

(2, 2)

In [47]:
# You can sum the columns

b.sum(axis=1) #kolum

array([3, 4])

In [48]:
b.shape

(2, 2)

### More Array Operations

`Maximum, minimum, sum, mean, product, standard deviation, and more`

```py
data.max()
data.min()
data.sum()
```

In [83]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [84]:
A.sum()

4.8595784

In [85]:
A.min()

0.05093587

In [89]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [86]:
A.max()

0.82485143

In [87]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [88]:
A.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [90]:
A.std()

0.21392120766089617

# Latihan

In [49]:
import numpy as np
x = np.arange(2,11).reshape(3,3)
print(x)
print(x.shape)
print(x.ndim)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
2


In [50]:
arr = np.array(70)
print(arr)
print(arr.ndim) #0 karena skalar

70
0


In [51]:
arr = np.array([[1,2,3],[4,5,6],[4,5,6]])
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]
 [4 5 6]]


(3, 3)

In [52]:
arr = np.array ([[[1,2,3],
                [4,5,6]],
                
                [[1,2,3],
                [4,5,6]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [53]:
array_tes = np.array([[3,7,10,2],[3,7,10,2]], ndmin=3) #ndmin disini digunakan untuk mengubah dimensi
print(array_tes.ndim)
print(array_tes.shape)
print(array_tes)

3
(1, 2, 4)
[[[ 3  7 10  2]
  [ 3  7 10  2]]]


In [54]:
import numpy as np
array_tes = np.array([3,10,3,2])

print(array_tes[3] + array_tes[2])

5


In [55]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[0,4]) # 0 =baris, 4 =kolum, baris ke-0, kolum ke-4
print(arr.ndim)
print(arr.shape)
print(arr[:1,3]) # baris 0-0, kolum 3
print(arr[:3, :3]) # baris 0-2, kolum 0-2
print(arr[:3, :1]) #baris 0-2, kolum 0-0
print(arr[-1,-1]) #baris -1, kolum -1

10
2
(2, 5)
[9]
[[6 7 8]
 [1 2 3]]
[[6]
 [1]]
5


In [56]:
arr = np.array([[[1,2,3], [4,5,6]], 
                [[7,8,9], [10,11,12]]])

print(arr[:, 1, 2])
print(arr.shape)

print(arr[1,0,0]) # baris ke 1, kolum ke-0, step 0
print(arr[:1,0,0]) # baris 0-0, kolum ke-0, step 0
print(arr[:2,0,0]) # baris 0-1, kolum ke-0, step 0
print(arr[:2,0,2]) # baris 0-1, kolum ke-0, step 2
print(arr[:2,1,2]) # baris 0-1, kolum ke-1, step 2
print(arr[:1,:2,1]) # baris 0:0, kolum 0-1, step 1
print(arr[:1,:2,:1]) #baris 0:0, kolum 0-1, step 0-0

[ 6 12]
(2, 2, 3)
7
[1]
[1 7]
[3 9]
[ 6 12]
[[2 5]]
[[[1]
  [4]]]


In [57]:
arr = np.array([4,5,6,7,1,2,3])

print(arr[1:6:4]) # indeks 1-5, step 4
print(arr[1:5:4]) # indeks 1-4, step 4nya tidak ada

[5 2]
[5]


In [58]:
arr = np.array([2,2,7,4,5,6,7,8,10])
print(arr[2:8:3]) # indeks 2-7, step 3
print(arr[::3]) # indeks 0-semua, step 3

[7 6]
[2 4 7]


In [59]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4]) #baris 0-1, kolum 1-3
print(arr[0:2, 1:3]) #baris 0-1, kolum 1-2

[[2 3 4]
 [7 8 9]]
[[2 3]
 [7 8]]


In [60]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(1, 2, -1) #baris 2, kolum 2, step -1
# -1, announ dimension, otomatis mengisi jumlah dimensi, karena -1 artinya akhir
print(newarr, "\n")
print(newarr.shape)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]] 

(1, 2, 6)
